package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Campaing generated by hbm2java
 */
public class Campaing  implements java.io.Serializable {


     private int id;
     private String name;
     private Set storeCampaings = new HashSet(0);

    public Campaing() {
    }

	
    public Campaing(int id) {
        this.id = id;
    }
    public Campaing(int id, String name, Set storeCampaings) {
       this.id = id;
       this.name = name;
       this.storeCampaings = storeCampaings;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getStoreCampaings() {
        return this.storeCampaings;
    }
    
    public void setStoreCampaings(Set storeCampaings) {
        this.storeCampaings = storeCampaings;
    }




}


