package starcarrental.Model;
// Generated 12/10/2019 05:34:53 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Car generated by hbm2java
 */
public class Car  implements java.io.Serializable {


     private int id;
     private CarCategory carCategory;
     private Store store;
     private String brand;
     private String model;
     private int modelYear;
     private String color;
     private int doorsNumber;
     private boolean automaticTransmission;
     private int seatingCapacity;
     private double luggageCapacity;
     private boolean diesel;
     private double kmPerLitre;
     private int ageRestrictions;
     private String generalRestriction;
     private String insuranceRestriction;
     private String numberPlate;
     private boolean available;
     private boolean damaged;
     private Set carDamageHistories = new HashSet(0);
     private Set carRentalManagements = new HashSet(0);
     private Set carMaintananceHistories = new HashSet(0);

    public Car() {
    }

	
    public Car(int id, CarCategory carCategory, Store store, String brand, String model, int modelYear, String color, int doorsNumber, boolean automaticTransmission, int seatingCapacity, double luggageCapacity, boolean diesel, double kmPerLitre, int ageRestrictions, String numberPlate, boolean available, boolean damaged) {
        this.id = id;
        this.carCategory = carCategory;
        this.store = store;
        this.brand = brand;
        this.model = model;
        this.modelYear = modelYear;
        this.color = color;
        this.doorsNumber = doorsNumber;
        this.automaticTransmission = automaticTransmission;
        this.seatingCapacity = seatingCapacity;
        this.luggageCapacity = luggageCapacity;
        this.diesel = diesel;
        this.kmPerLitre = kmPerLitre;
        this.ageRestrictions = ageRestrictions;
        this.numberPlate = numberPlate;
        this.available = available;
        this.damaged = damaged;
    }
    public Car(int id, CarCategory carCategory, Store store, String brand, String model, int modelYear, String color, int doorsNumber, boolean automaticTransmission, int seatingCapacity, double luggageCapacity, boolean diesel, double kmPerLitre, int ageRestrictions, String generalRestriction, String insuranceRestriction, String numberPlate, boolean available, boolean damaged, Set carDamageHistories, Set carRentalManagements, Set carMaintananceHistories) {
       this.id = id;
       this.carCategory = carCategory;
       this.store = store;
       this.brand = brand;
       this.model = model;
       this.modelYear = modelYear;
       this.color = color;
       this.doorsNumber = doorsNumber;
       this.automaticTransmission = automaticTransmission;
       this.seatingCapacity = seatingCapacity;
       this.luggageCapacity = luggageCapacity;
       this.diesel = diesel;
       this.kmPerLitre = kmPerLitre;
       this.ageRestrictions = ageRestrictions;
       this.generalRestriction = generalRestriction;
       this.insuranceRestriction = insuranceRestriction;
       this.numberPlate = numberPlate;
       this.available = available;
       this.damaged = damaged;
       this.carDamageHistories = carDamageHistories;
       this.carRentalManagements = carRentalManagements;
       this.carMaintananceHistories = carMaintananceHistories;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CarCategory getCarCategory() {
        return this.carCategory;
    }
    
    public void setCarCategory(CarCategory carCategory) {
        this.carCategory = carCategory;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public int getModelYear() {
        return this.modelYear;
    }
    
    public void setModelYear(int modelYear) {
        this.modelYear = modelYear;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getDoorsNumber() {
        return this.doorsNumber;
    }
    
    public void setDoorsNumber(int doorsNumber) {
        this.doorsNumber = doorsNumber;
    }
    public boolean isAutomaticTransmission() {
        return this.automaticTransmission;
    }
    
    public void setAutomaticTransmission(boolean automaticTransmission) {
        this.automaticTransmission = automaticTransmission;
    }
    public int getSeatingCapacity() {
        return this.seatingCapacity;
    }
    
    public void setSeatingCapacity(int seatingCapacity) {
        this.seatingCapacity = seatingCapacity;
    }
    public double getLuggageCapacity() {
        return this.luggageCapacity;
    }
    
    public void setLuggageCapacity(double luggageCapacity) {
        this.luggageCapacity = luggageCapacity;
    }
    public boolean isDiesel() {
        return this.diesel;
    }
    
    public void setDiesel(boolean diesel) {
        this.diesel = diesel;
    }
    public double getKmPerLitre() {
        return this.kmPerLitre;
    }
    
    public void setKmPerLitre(double kmPerLitre) {
        this.kmPerLitre = kmPerLitre;
    }
    public int getAgeRestrictions() {
        return this.ageRestrictions;
    }
    
    public void setAgeRestrictions(int ageRestrictions) {
        this.ageRestrictions = ageRestrictions;
    }
    public String getGeneralRestriction() {
        return this.generalRestriction;
    }
    
    public void setGeneralRestriction(String generalRestriction) {
        this.generalRestriction = generalRestriction;
    }
    public String getInsuranceRestriction() {
        return this.insuranceRestriction;
    }
    
    public void setInsuranceRestriction(String insuranceRestriction) {
        this.insuranceRestriction = insuranceRestriction;
    }
    public String getNumberPlate() {
        return this.numberPlate;
    }
    
    public void setNumberPlate(String numberPlate) {
        this.numberPlate = numberPlate;
    }
    public boolean isAvailable() {
        return this.available;
    }
    
    public void setAvailable(boolean available) {
        this.available = available;
    }
    public boolean isDamaged() {
        return this.damaged;
    }
    
    public void setDamaged(boolean damaged) {
        this.damaged = damaged;
    }
    public Set getCarDamageHistories() {
        return this.carDamageHistories;
    }
    
    public void setCarDamageHistories(Set carDamageHistories) {
        this.carDamageHistories = carDamageHistories;
    }
    public Set getCarRentalManagements() {
        return this.carRentalManagements;
    }
    
    public void setCarRentalManagements(Set carRentalManagements) {
        this.carRentalManagements = carRentalManagements;
    }
    public Set getCarMaintananceHistories() {
        return this.carMaintananceHistories;
    }
    
    public void setCarMaintananceHistories(Set carMaintananceHistories) {
        this.carMaintananceHistories = carMaintananceHistories;
    }




}


