package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CarCategory generated by hbm2java
 */
public class CarCategory  implements java.io.Serializable {


     private int id;
     private String name;
     private String abbr;
     private Set carFeeByCategories = new HashSet(0);
     private Set cars = new HashSet(0);

    public CarCategory() {
    }

	
    public CarCategory(int id, String name, String abbr) {
        this.id = id;
        this.name = name;
        this.abbr = abbr;
    }
    public CarCategory(int id, String name, String abbr, Set carFeeByCategories, Set cars) {
       this.id = id;
       this.name = name;
       this.abbr = abbr;
       this.carFeeByCategories = carFeeByCategories;
       this.cars = cars;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAbbr() {
        return this.abbr;
    }
    
    public void setAbbr(String abbr) {
        this.abbr = abbr;
    }
    public Set getCarFeeByCategories() {
        return this.carFeeByCategories;
    }
    
    public void setCarFeeByCategories(Set carFeeByCategories) {
        this.carFeeByCategories = carFeeByCategories;
    }
    public Set getCars() {
        return this.cars;
    }
    
    public void setCars(Set cars) {
        this.cars = cars;
    }




}


