package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CarDamageHistory generated by hbm2java
 */
public class CarDamageHistory  implements java.io.Serializable {


     private int id;
     private Car car;
     private int idCarRentalManagement;
     private int idEmployee;
     private Date startDate;
     private Date finishDate;
     private double currentKm;
     private String note;
     private double cost;
     private long completed;

    public CarDamageHistory() {
    }

	
    public CarDamageHistory(int id, Car car, int idCarRentalManagement, int idEmployee, Date startDate, Date finishDate, double currentKm, double cost, long completed) {
        this.id = id;
        this.car = car;
        this.idCarRentalManagement = idCarRentalManagement;
        this.idEmployee = idEmployee;
        this.startDate = startDate;
        this.finishDate = finishDate;
        this.currentKm = currentKm;
        this.cost = cost;
        this.completed = completed;
    }
    public CarDamageHistory(int id, Car car, int idCarRentalManagement, int idEmployee, Date startDate, Date finishDate, double currentKm, String note, double cost, long completed) {
       this.id = id;
       this.car = car;
       this.idCarRentalManagement = idCarRentalManagement;
       this.idEmployee = idEmployee;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.currentKm = currentKm;
       this.note = note;
       this.cost = cost;
       this.completed = completed;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public int getIdCarRentalManagement() {
        return this.idCarRentalManagement;
    }
    
    public void setIdCarRentalManagement(int idCarRentalManagement) {
        this.idCarRentalManagement = idCarRentalManagement;
    }
    public int getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(int idEmployee) {
        this.idEmployee = idEmployee;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    public double getCurrentKm() {
        return this.currentKm;
    }
    
    public void setCurrentKm(double currentKm) {
        this.currentKm = currentKm;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public double getCost() {
        return this.cost;
    }
    
    public void setCost(double cost) {
        this.cost = cost;
    }
    public long getCompleted() {
        return this.completed;
    }
    
    public void setCompleted(long completed) {
        this.completed = completed;
    }




}


