package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1



/**
 * CarFeeByCategory generated by hbm2java
 */
public class CarFeeByCategory  implements java.io.Serializable {


     private int id;
     private CarCategory carCategory;
     private Store store;
     private double dailyCharge;
     private Double weeklyCharge;
     private Double weekendCharge;
     private Double addKmCharge;
     private Double totalPerCategory;
     private Double rentedPerCategory;

    public CarFeeByCategory() {
    }

	
    public CarFeeByCategory(int id, CarCategory carCategory, Store store, double dailyCharge) {
        this.id = id;
        this.carCategory = carCategory;
        this.store = store;
        this.dailyCharge = dailyCharge;
    }
    public CarFeeByCategory(int id, CarCategory carCategory, Store store, double dailyCharge, Double weeklyCharge, Double weekendCharge, Double addKmCharge, Double totalPerCategory, Double rentedPerCategory) {
       this.id = id;
       this.carCategory = carCategory;
       this.store = store;
       this.dailyCharge = dailyCharge;
       this.weeklyCharge = weeklyCharge;
       this.weekendCharge = weekendCharge;
       this.addKmCharge = addKmCharge;
       this.totalPerCategory = totalPerCategory;
       this.rentedPerCategory = rentedPerCategory;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CarCategory getCarCategory() {
        return this.carCategory;
    }
    
    public void setCarCategory(CarCategory carCategory) {
        this.carCategory = carCategory;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public double getDailyCharge() {
        return this.dailyCharge;
    }
    
    public void setDailyCharge(double dailyCharge) {
        this.dailyCharge = dailyCharge;
    }
    public Double getWeeklyCharge() {
        return this.weeklyCharge;
    }
    
    public void setWeeklyCharge(Double weeklyCharge) {
        this.weeklyCharge = weeklyCharge;
    }
    public Double getWeekendCharge() {
        return this.weekendCharge;
    }
    
    public void setWeekendCharge(Double weekendCharge) {
        this.weekendCharge = weekendCharge;
    }
    public Double getAddKmCharge() {
        return this.addKmCharge;
    }
    
    public void setAddKmCharge(Double addKmCharge) {
        this.addKmCharge = addKmCharge;
    }
    public Double getTotalPerCategory() {
        return this.totalPerCategory;
    }
    
    public void setTotalPerCategory(Double totalPerCategory) {
        this.totalPerCategory = totalPerCategory;
    }
    public Double getRentedPerCategory() {
        return this.rentedPerCategory;
    }
    
    public void setRentedPerCategory(Double rentedPerCategory) {
        this.rentedPerCategory = rentedPerCategory;
    }




}


