package starcarrental.Model;
// Generated 12/10/2019 05:34:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * CarMaintananceHistory generated by hbm2java
 */
public class CarMaintananceHistory  implements java.io.Serializable {


     private int id;
     private Car car;
     private MaintenanceType maintenanceType;
     private int idEmployee;
     private int orderNumber;
     private Date startDate;
     private Date finishDate;
     private String notes;
     private boolean completed;

    public CarMaintananceHistory() {
    }

	
    public CarMaintananceHistory(int id, Car car, MaintenanceType maintenanceType, int idEmployee, int orderNumber, boolean completed) {
        this.id = id;
        this.car = car;
        this.maintenanceType = maintenanceType;
        this.idEmployee = idEmployee;
        this.orderNumber = orderNumber;
        this.completed = completed;
    }
    public CarMaintananceHistory(int id, Car car, MaintenanceType maintenanceType, int idEmployee, int orderNumber, Date startDate, Date finishDate, String notes, boolean completed) {
       this.id = id;
       this.car = car;
       this.maintenanceType = maintenanceType;
       this.idEmployee = idEmployee;
       this.orderNumber = orderNumber;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.notes = notes;
       this.completed = completed;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public MaintenanceType getMaintenanceType() {
        return this.maintenanceType;
    }
    
    public void setMaintenanceType(MaintenanceType maintenanceType) {
        this.maintenanceType = maintenanceType;
    }
    public int getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(int idEmployee) {
        this.idEmployee = idEmployee;
    }
    public int getOrderNumber() {
        return this.orderNumber;
    }
    
    public void setOrderNumber(int orderNumber) {
        this.orderNumber = orderNumber;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }
    public boolean isCompleted() {
        return this.completed;
    }
    
    public void setCompleted(boolean completed) {
        this.completed = completed;
    }




}


