package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CarRentalManagement generated by hbm2java
 */
public class CarRentalManagement  implements java.io.Serializable {


     private int id;
     private Car car;
     private User user;
     private Integer quotationNumber;
     private Date quotationDate;
     private Double quotationPrice;
     private Boolean webQuotation;
     private Integer bookNumber;
     private Integer rentalAgreementNumber;
     private Date expectedStartRent;
     private Date startRent;
     private Date expectedFinishRent;
     private Date finishRent;
     private Double startKm;
     private Double finishKm;
     private Double petrol;
     private String promotionalCode;
     private Boolean excessReduction;
     private Double deposit;
     private Set payments = new HashSet(0);
     private Set driverAlloweds = new HashSet(0);

    public CarRentalManagement() {
    }

	
    public CarRentalManagement(int id, Car car, User user) {
        this.id = id;
        this.car = car;
        this.user = user;
    }
    public CarRentalManagement(int id, Car car, User user, Integer quotationNumber, Date quotationDate, Double quotationPrice, Boolean webQuotation, Integer bookNumber, Integer rentalAgreementNumber, Date expectedStartRent, Date startRent, Date expectedFinishRent, Date finishRent, Double startKm, Double finishKm, Double petrol, String promotionalCode, Boolean excessReduction, Double deposit, Set payments, Set driverAlloweds) {
       this.id = id;
       this.car = car;
       this.user = user;
       this.quotationNumber = quotationNumber;
       this.quotationDate = quotationDate;
       this.quotationPrice = quotationPrice;
       this.webQuotation = webQuotation;
       this.bookNumber = bookNumber;
       this.rentalAgreementNumber = rentalAgreementNumber;
       this.expectedStartRent = expectedStartRent;
       this.startRent = startRent;
       this.expectedFinishRent = expectedFinishRent;
       this.finishRent = finishRent;
       this.startKm = startKm;
       this.finishKm = finishKm;
       this.petrol = petrol;
       this.promotionalCode = promotionalCode;
       this.excessReduction = excessReduction;
       this.deposit = deposit;
       this.payments = payments;
       this.driverAlloweds = driverAlloweds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Car getCar() {
        return this.car;
    }
    
    public void setCar(Car car) {
        this.car = car;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getQuotationNumber() {
        return this.quotationNumber;
    }
    
    public void setQuotationNumber(Integer quotationNumber) {
        this.quotationNumber = quotationNumber;
    }
    public Date getQuotationDate() {
        return this.quotationDate;
    }
    
    public void setQuotationDate(Date quotationDate) {
        this.quotationDate = quotationDate;
    }
    public Double getQuotationPrice() {
        return this.quotationPrice;
    }
    
    public void setQuotationPrice(Double quotationPrice) {
        this.quotationPrice = quotationPrice;
    }
    public Boolean getWebQuotation() {
        return this.webQuotation;
    }
    
    public void setWebQuotation(Boolean webQuotation) {
        this.webQuotation = webQuotation;
    }
    public Integer getBookNumber() {
        return this.bookNumber;
    }
    
    public void setBookNumber(Integer bookNumber) {
        this.bookNumber = bookNumber;
    }
    public Integer getRentalAgreementNumber() {
        return this.rentalAgreementNumber;
    }
    
    public void setRentalAgreementNumber(Integer rentalAgreementNumber) {
        this.rentalAgreementNumber = rentalAgreementNumber;
    }
    public Date getExpectedStartRent() {
        return this.expectedStartRent;
    }
    
    public void setExpectedStartRent(Date expectedStartRent) {
        this.expectedStartRent = expectedStartRent;
    }
    public Date getStartRent() {
        return this.startRent;
    }
    
    public void setStartRent(Date startRent) {
        this.startRent = startRent;
    }
    public Date getExpectedFinishRent() {
        return this.expectedFinishRent;
    }
    
    public void setExpectedFinishRent(Date expectedFinishRent) {
        this.expectedFinishRent = expectedFinishRent;
    }
    public Date getFinishRent() {
        return this.finishRent;
    }
    
    public void setFinishRent(Date finishRent) {
        this.finishRent = finishRent;
    }
    public Double getStartKm() {
        return this.startKm;
    }
    
    public void setStartKm(Double startKm) {
        this.startKm = startKm;
    }
    public Double getFinishKm() {
        return this.finishKm;
    }
    
    public void setFinishKm(Double finishKm) {
        this.finishKm = finishKm;
    }
    public Double getPetrol() {
        return this.petrol;
    }
    
    public void setPetrol(Double petrol) {
        this.petrol = petrol;
    }
    public String getPromotionalCode() {
        return this.promotionalCode;
    }
    
    public void setPromotionalCode(String promotionalCode) {
        this.promotionalCode = promotionalCode;
    }
    public Boolean getExcessReduction() {
        return this.excessReduction;
    }
    
    public void setExcessReduction(Boolean excessReduction) {
        this.excessReduction = excessReduction;
    }
    public Double getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(Double deposit) {
        this.deposit = deposit;
    }
    public Set getPayments() {
        return this.payments;
    }
    
    public void setPayments(Set payments) {
        this.payments = payments;
    }
    public Set getDriverAlloweds() {
        return this.driverAlloweds;
    }
    
    public void setDriverAlloweds(Set driverAlloweds) {
        this.driverAlloweds = driverAlloweds;
    }




}


