package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CreditCardFranchise generated by hbm2java
 */
public class CreditCardFranchise  implements java.io.Serializable {


     private int id;
     private String type;
     private Set creditCards = new HashSet(0);

    public CreditCardFranchise() {
    }

	
    public CreditCardFranchise(int id) {
        this.id = id;
    }
    public CreditCardFranchise(int id, String type, Set creditCards) {
       this.id = id;
       this.type = type;
       this.creditCards = creditCards;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getCreditCards() {
        return this.creditCards;
    }
    
    public void setCreditCards(Set creditCards) {
        this.creditCards = creditCards;
    }




}


