package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1



/**
 * DriverAllowed generated by hbm2java
 */
public class DriverAllowed  implements java.io.Serializable {


     private int id;
     private CarRentalManagement carRentalManagement;
     private Driver driver;

    public DriverAllowed() {
    }

    public DriverAllowed(int id, CarRentalManagement carRentalManagement, Driver driver) {
       this.id = id;
       this.carRentalManagement = carRentalManagement;
       this.driver = driver;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CarRentalManagement getCarRentalManagement() {
        return this.carRentalManagement;
    }
    
    public void setCarRentalManagement(CarRentalManagement carRentalManagement) {
        this.carRentalManagement = carRentalManagement;
    }
    public Driver getDriver() {
        return this.driver;
    }
    
    public void setDriver(Driver driver) {
        this.driver = driver;
    }




}


