package starcarrental.Model;
// Generated 12/10/2019 05:34:53 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Driver generated by hbm2java
 */
public class Driver  implements java.io.Serializable {


     private int id;
     private String name;
     private String lastName;
     private String address;
     private Date dateOfBirth;
     private String email;
     private String licenseNumber;
     private String licenseState;
     private Set driverAlloweds = new HashSet(0);

    public Driver() {
    }

	
    public Driver(int id, String name, String lastName, String address, Date dateOfBirth, String licenseNumber, String licenseState) {
        this.id = id;
        this.name = name;
        this.lastName = lastName;
        this.address = address;
        this.dateOfBirth = dateOfBirth;
        this.licenseNumber = licenseNumber;
        this.licenseState = licenseState;
    }
    public Driver(int id, String name, String lastName, String address, Date dateOfBirth, String email, String licenseNumber, String licenseState, Set driverAlloweds) {
       this.id = id;
       this.name = name;
       this.lastName = lastName;
       this.address = address;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.licenseNumber = licenseNumber;
       this.licenseState = licenseState;
       this.driverAlloweds = driverAlloweds;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getLicenseNumber() {
        return this.licenseNumber;
    }
    
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }
    public String getLicenseState() {
        return this.licenseState;
    }
    
    public void setLicenseState(String licenseState) {
        this.licenseState = licenseState;
    }
    public Set getDriverAlloweds() {
        return this.driverAlloweds;
    }
    
    public void setDriverAlloweds(Set driverAlloweds) {
        this.driverAlloweds = driverAlloweds;
    }




}


