package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmployeeRol generated by hbm2java
 */
public class EmployeeRol  implements java.io.Serializable {


     private int id;
     private String name;
     private String note;
     private Set employees = new HashSet(0);

    public EmployeeRol() {
    }

	
    public EmployeeRol(int id, String name) {
        this.id = id;
        this.name = name;
    }
    public EmployeeRol(int id, String name, String note, Set employees) {
       this.id = id;
       this.name = name;
       this.note = note;
       this.employees = employees;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


