package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * IdentificationType generated by hbm2java
 */
public class IdentificationType  implements java.io.Serializable {


     private int id;
     private String type;
     private Set userIdifications = new HashSet(0);

    public IdentificationType() {
    }

	
    public IdentificationType(int id) {
        this.id = id;
    }
    public IdentificationType(int id, String type, Set userIdifications) {
       this.id = id;
       this.type = type;
       this.userIdifications = userIdifications;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getUserIdifications() {
        return this.userIdifications;
    }
    
    public void setUserIdifications(Set userIdifications) {
        this.userIdifications = userIdifications;
    }




}


