package starcarrental.Model;
// Generated 12/10/2019 05:34:53 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StoreCampaing generated by hbm2java
 */
public class StoreCampaing  implements java.io.Serializable {


     private int id;
     private Campaing campaing;
     private Store store;
     private int idCategory;
     private Date startDate;
     private Date finishDate;
     private double discount;

    public StoreCampaing() {
    }

    public StoreCampaing(int id, Campaing campaing, Store store, int idCategory, Date startDate, Date finishDate, double discount) {
       this.id = id;
       this.campaing = campaing;
       this.store = store;
       this.idCategory = idCategory;
       this.startDate = startDate;
       this.finishDate = finishDate;
       this.discount = discount;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Campaing getCampaing() {
        return this.campaing;
    }
    
    public void setCampaing(Campaing campaing) {
        this.campaing = campaing;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public int getIdCategory() {
        return this.idCategory;
    }
    
    public void setIdCategory(int idCategory) {
        this.idCategory = idCategory;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getFinishDate() {
        return this.finishDate;
    }
    
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }
    public double getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(double discount) {
        this.discount = discount;
    }




}


