package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int id;
     private String name;
     private String lastName;
     private Date dateOfBirth;
     private String email;
     private String password;
     private Set employees = new HashSet(0);
     private Set carRentalManagements = new HashSet(0);
     private Set userIdifications = new HashSet(0);
     private Set userCreditCards = new HashSet(0);

    public User() {
    }

	
    public User(int id, String name, String lastName, Date dateOfBirth, String email, String password) {
        this.id = id;
        this.name = name;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.email = email;
        this.password = password;
    }
    public User(int id, String name, String lastName, Date dateOfBirth, String email, String password, Set employees, Set carRentalManagements, Set userIdifications, Set userCreditCards) {
       this.id = id;
       this.name = name;
       this.lastName = lastName;
       this.dateOfBirth = dateOfBirth;
       this.email = email;
       this.password = password;
       this.employees = employees;
       this.carRentalManagements = carRentalManagements;
       this.userIdifications = userIdifications;
       this.userCreditCards = userCreditCards;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }
    public Set getCarRentalManagements() {
        return this.carRentalManagements;
    }
    
    public void setCarRentalManagements(Set carRentalManagements) {
        this.carRentalManagements = carRentalManagements;
    }
    public Set getUserIdifications() {
        return this.userIdifications;
    }
    
    public void setUserIdifications(Set userIdifications) {
        this.userIdifications = userIdifications;
    }
    public Set getUserCreditCards() {
        return this.userCreditCards;
    }
    
    public void setUserCreditCards(Set userCreditCards) {
        this.userCreditCards = userCreditCards;
    }




}


