package starcarrental.Model;
// Generated 12/10/2019 10:35:55 AM by Hibernate Tools 4.3.1



/**
 * UserIdification generated by hbm2java
 */
public class UserIdification  implements java.io.Serializable {


     private int id;
     private IdentificationType identificationType;
     private User user;
     private String value;

    public UserIdification() {
    }

    public UserIdification(int id, IdentificationType identificationType, User user, String value) {
       this.id = id;
       this.identificationType = identificationType;
       this.user = user;
       this.value = value;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public IdentificationType getIdentificationType() {
        return this.identificationType;
    }
    
    public void setIdentificationType(IdentificationType identificationType) {
        this.identificationType = identificationType;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }




}


