package starcarrental.Model;
// Generated 12/10/2019 05:34:53 PM by Hibernate Tools 4.3.1



/**
 * UserCreditCard generated by hbm2java
 */
public class UserCreditCard  implements java.io.Serializable {


     private int id;
     private CreditCard creditCard;
     private User user;

    public UserCreditCard() {
    }

	
    public UserCreditCard(int id, User user) {
        this.id = id;
        this.user = user;
    }
    public UserCreditCard(int id, CreditCard creditCard, User user) {
       this.id = id;
       this.creditCard = creditCard;
       this.user = user;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CreditCard getCreditCard() {
        return this.creditCard;
    }
    
    public void setCreditCard(CreditCard creditCard) {
        this.creditCard = creditCard;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }




}


